# Generated by Django 3.2.8 on 2021-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('is_new', models.BooleanField(default=True)),
                ('features', models.TextField()),
            ],
        ),
    ]
