# Generated by Django 3.2.8 on 2021-10-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mobile_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='ram',
        ),
    ]
